avatar: https://cdn.jsdelivr.net/gh/5ime/img/avatar.jpg # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
    path: https://p1.meituan.net/csc/ea3f6516d0622b0b3c5934d6a3b8e69a405101.png
    width: 1280
    height: 726
favicon:
  href: /favicon.ico # 网站图标
  type: image/x-icon # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能
  wordCount: true # 是否开启文章字数统计 (true, false)
  copyCode: true # 是否允许复制代码块
  highlight: true # 是否开启代码高亮

imageCDN: # 图片 CDN 功能
  enable: false # 开启该功能  
  origin: /../../images/ # 图片原始目录
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # 图片 CDN 域名

# 自定义样式，启用后可在站点的source文件夹下新建custom.css自定义站点样式
customStyles:
  - custom.css
  
# 附加图标库 使用说明：https://docs.nexmoe.com/config/icon
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
    回到首页:
        - /
        - icon-home
    文章归档:
        - /archive
        - icon-container
    关于我:
        - /about
        - icon-info-circle
    留言板: 
        - /guestbook
    友人帐: 
        - /links
        - icon-appstore-fill

widgets:
    - name: likeme
      enable: true
    - name: search
      enable: true
      options: 
        search: 
            type: local # 可选engine（用搜索引擎搜索）、swiftype、或local（本地搜索）
            url: https://www.google.com/search?q=5ime.cn # 搜索引擎地址，在type为swiftype时无效 e.g:https://www.google.com/search?q={你的博客链接}
            id: <swiftype-id> # swiftype的id，见启用教程。在type为engine时无效
    - name: social
      enable: true
      options: 
        social:
            哔哩哔哩:
                - https://space.bilibili.com/208224743
                - icon-bilibili
                - rgb(231, 106, 141)
                - rgba(231, 106, 141, .15)
            GitHub:
                - https://github.com/5ime/
                - icon-github
                - rgb(25, 23, 23)
                - rgba(25, 23, 23, .15)
            # Telegram:
            #     - https://t.me/iami_bot
            #     - icon-telegram
            #     - rgb(100, 185, 255);
            #     - rgba(39, 167, 229, .1)
            # Twitter:
            #     - https://twitter.com/iami233
            #     - icon-twitter
            #     - rgb(100, 185, 255);
            #     - rgba(29,161,242,.1)
    - name: category
      enable: true
    - name: tagcloud
      enable: true
      options: 
        maxTagcloud: 10  # 标签云组件显示的标签数量，0 表示不限制
    - name: hitokoto # 一言 widget
      enable: false
      options: 
        widgetHitokoto: # 一言组件
            loading_placeholder: '🚀 获取中...' # 正在一言时的占位符
            loading_error_placeholder: '🐞 获取失败...' # 加载一言失败时的占位符
            category: # 一言句子类型（可选），不配置的话随机获取，详见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    - name: archive #settings: widgetAchive
      enable: true
      options:
        widgetAchive: #文章归档组件
            archive_type: 'year' #按月展示还是按年展示
            show_count: true  #是否展示数量
    - name: recent_posts
      enable: false
    - name: link #settings: widgetLink
      enable: false
      options: 
        widgetLink: #链接组件
            - title: 折影轻梦
              img: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/avatar.png
              link : https://nexmoe.com/

copyTip: "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url" # 自定义复制版权文案,使用 %url 代替当前页面URL, 修改为false禁用

slotHead: | 
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-xxxxxxxxxxxxx"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-xxxxxxxxxxxxx');
  </script>

slotFooter: | 
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxxxxxxxxxxxx" crossorigin="anonymous"></script>

# 自定义侧边栏尾部内容
slotSidebar: |
  <br><a href="https://github.com/5ime/hexo-theme-i" target="_blank">Theme</a> & <a href="https://5ime.cn/atom.xml" target="_blank">RSS</a> & <a href="https://5ime.cn/sitemap.xml" target="_blank">Sitemap</a>

# 评论框插槽
slotComment: | 
  <script src="https://unpkg.com/@waline/client@v2/dist/waline.js"></script><link  rel="stylesheet"  href="https://unpkg.com/@waline/client@v2/dist/waline.css"/><div id="waline"></div><script>const locale = {placeholder: "🚀评论和回复支持Markdown\n📌请务必填写邮箱 用以接收评论回复提醒~"};Waline.init({el: "#waline",serverURL: "https://comment.5ime.cn",locale});</script>

slotCopyright: | 
  <strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可

slotArticleEnd: | 
  <ins class="adsbygoogle"
   style="display:block"
   data-ad-client="ca-pub-xxxxxxxxxxxxx"
   data-ad-slot="xxxxxxxxxxxxx"
   data-ad-format="auto"
   data-full-width-responsive="true"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
